/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.5/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("com.diffplug.spotless") version "7.0.0.BETA2"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)
    implementation("org.apache.flink:flink-json:1.20.0")
    compileOnly("org.apache.flink:flink-streaming-java:1.20.0")
    implementation("redis.clients:jedis:5.1.5")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    implementation("org.apache.flink:flink-connector-kafka:3.0.0-1.17")
    // This dependency is used by the application.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

application {
    // Define the main class for the application.
    mainClass.set("taxi.operators.App")
}
spotless {
    java {

        // Choose one of these formatters.
        googleJavaFormat()

    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
